### ISSUE TITLE
Unable to reference entities

### ISSUE THREAD

**Issue by Jameskmonger** [noodlecrate/poseidon#15]
Hi @jamesrichford,

I'm struggling with referencing [poseidon-entities](https://github.com/noodlecrate/poseidon-entities) in this project.

I have installed it via `npm install noodlecrate-poseidon-entities --save`, and so it gets [typings.d.ts](https://github.com/noodlecrate/poseidon-entities/blob/master/typings.d.ts) referenced correctly (as it's given in the other project's [package.json](https://github.com/noodlecrate/poseidon-entities/blob/master/package.json)).

However when I then try to use the entities, like this:

```
import * as Entities from 'noodlecrate-poseidon-entities';
```

I get these errors:

> TS Error
> File 'C:/Users/james.monger/Desktop/js/p/poseidon/node_modules/noodlecrate-poseidon-entities/typings.d.ts' is not a module.
> at line 3 col 27 in src\managers\brand-manager.ts
> 
> TS Error
> Exported external package typings file 'C:/Users/james.monger/Desktop/js/p/poseidon/node_modules/noodlecrate-poseidon-entities/typings.d.ts' is not a module. Please contact the package author to update the package definition.
> at line 3 col 27 in src\managers\brand-manager.ts

**Comment by Jameskmonger** [comment]
If you can't help I think only @basarat will be able to :(

**Comment by Jameskmonger** [comment]
@remojansen Are you able to take a look at this for me please? :P

**Comment by jamesadarich** [comment]
I'll have a peak now @jameskmonger but on phone so don't expect much ;P

**Comment by jamesadarich** [comment]
Module name is "poseidon-entities" `import * as Entities from 'poseidon-entities';`?

**Comment by jamesadarich** [comment]
/ probably rename the module definition so it's aligned with npm name

**Comment by remojansen** [comment]
I thin it can be what @jamesrichford just mentioned or that your path `"main": "./build/index.js",` in package.json of poseidon-entities is not right?

**Comment by jamesadarich** [comment]
Yeah good point @remojansen looking at the `tsconfig.json` there should be a module in that file but may be missing in the npm distribution

**Comment by Jameskmonger** [comment]
When the package is published, it is built so `build/index.js` exists in the npm distribution :)

**Comment by Jameskmonger** [comment]
Sorted. Thanks for the help guys!

**Comment by remojansen** [comment]
No problem. Do you mind sharing what was the problem? Is always good to learn from issues :smile:

**Comment by Jameskmonger** [comment]
Of course! A couple of changes:
- Removing the `declare module "..."` from the typings file
- Exporting the objects directly

You can see the working typings version here: https://github.com/noodlecrate/poseidon-entities/blob/master/typings.d.ts

@remojansen
